FROM python:3.10-slim-buster

WORKDIR /backend-flask

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install opentelemetry-instrumentation

COPY . .

ENV FLASK_ENV=production
ENV FLASK_APP=app.py

EXPOSE 4567

CMD ["opentelemetry-instrument", "python3", "-m", "flask", "run", "--host=0.0.0.0", "--port=4567"]