# Use the official Node.js image from the Docker Hub
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Expose the port that the React app runs on
EXPOSE 3000

# Command to run the React application
CMD ["sh", "-c", "BACKEND_URL=${BACKEND_URL} npm start"]