# Build step #1: build the React front end
FROM node:14-alpine as build-step

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . .

# Build the React application
RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine

# Copy the built React application from the build step
COPY --from=build-step /app/build /usr/share/nginx/html

# Copy the Nginx configuration file into the container
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf

